### ISSUE TITLE
Bouncing send button

### ISSUE THREAD

**Issue by billybob35** [brandonhamilton/inputtoolbar#1]
Hello,

Great work! is there a way to fix the send button to the bottom of the toolbar?

**Comment by brandonhamilton** [comment]
Thanks for the feedback. 

The button is now anchored to the bottom of the toolbar - ref [Commit](https://github.com/brandonhamilton/inputtoolbar/commit/6a4575ed5154716cd467118f790c28ec77b90b1d).
