### ISSUE TITLE
enable "secureTextEntry" option

### ISSUE THREAD

**Issue by fabiosoft** [brandonhamilton/inputtoolbar#3]
i love your work, but it could be cooler if you add option for enable secureTextEntry for the input field.
thanks

**Comment by brandonhamilton** [comment]
Hi, 

  Thanks for the feedback.

Unfortunately, the toolbar uses a UITextView internally, which does not respond to the secureTextEntry trait.
For reference: http://stackoverflow.com/questions/2164809/uitextview-does-not-respect-the-securetextentry-property
The only way I can see around this is to set a custom font.

**Comment by fabiosoft** [comment]
Oh ok thanks
