### ISSUE TITLE
Is it usable on iPad?

### ISSUE THREAD

**Issue by mgrebenets** [brandonhamilton/inputtoolbar#6]
Hi, thanks for a great work!
I am trying to use input toolbar in universal app. It works fine on iPhone (both simulator and device), but on iPad I can't manage the same approach to work.
I simply add UIInputToolbar as a subview to my custom view, but on iPad it's displayed black and I can see some parts of "Send" text on the right. But then more comes, if I try to resize the view (by setting frame), that contains UIInputToolbar in its hierarchy, I got a crash like this:

```
'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 17.5]
```

This crash occurs only in simulator (iOS 5.1) but not on device, though on device I still have some black area instead of toolbar.

**Comment by mgrebenets** [comment]
I figured out why it's black on iPad. The image files names like "~iphone.png" are not properly picked up in universal app.

**Comment by brandonhamilton** [comment]
I have not tested or used this on the iPad. Feel free to fork the project and correct it for iPad use :)
